version: '3.8'

services:
  # Shared Infrastructure Services
  auth-service:
    build: ./backend
    ports: ["3001:3001"]
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  wallet-service:
    build: ./backend
    ports: ["3002:3002"]
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Matchmaking Service
  matchmaking-service:
    build: ./services/matchmaking-service
    ports: ["3003:3003"]
    environment:
      - NODE_ENV=development
      - PORT=3003
      - FRONTEND_URL=http://localhost:5173
      - CHESS_SERVICE_URL=http://chess-service:4001
      - CONNECT4_SERVICE_URL=http://connect4-service:4002
      - DIAMOND_SERVICE_URL=http://diamond-service:4003
    depends_on:
      - chess-service
      - connect4-service
      - diamond-service

  # Independent Game Services
  chess-service:
    build: ./services/chess-service
    ports: ["4001:4001"]
    environment:
      - NODE_ENV=development
      - PORT=4001
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./services/chess-service:/app
      - /app/node_modules

  connect4-service:
    build: ./services/connect4-service
    ports: ["4002:4002"]
    environment:
      - NODE_ENV=development
      - PORT=4002
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./services/connect4-service:/app
      - /app/node_modules

  diamond-service:
    build: ./services/diamond-service
    ports: ["4003:4003"]
    environment:
      - NODE_ENV=development
      - PORT=4003
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./services/diamond-service:/app
      - /app/node_modules

  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports: ["8080:8080"]
    environment:
      - NODE_ENV=development
      - PORT=8080
      - AUTH_SERVICE_URL=http://auth-service:3001
      - WALLET_SERVICE_URL=http://wallet-service:3002
      - MATCHMAKING_SERVICE_URL=http://matchmaking-service:3003
      - CHESS_SERVICE_URL=http://chess-service:4001
      - CONNECT4_SERVICE_URL=http://connect4-service:4002
      - DIAMOND_SERVICE_URL=http://diamond-service:4003
    depends_on:
      - auth-service
      - wallet-service
      - matchmaking-service
      - chess-service
      - connect4-service
      - diamond-service

  # Frontend
  frontend:
    build: .
    ports: ["5173:5173"]
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command: npm run dev

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redis_data:/data

  # Database
  database:
    image: postgres:15-alpine
    ports: ["5432:5432"]
    environment:
      - POSTGRES_DB=chanspaw
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data: 